### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-External-Tools#1]
Hi, it is already known already when will the market?

**Comment by emperorstarfinder** [comment]
I am working on this.  I just have been on vacation and just getting caught back up.  NOTE: This marketplace version will also work with VU to for the time being.

**Comment by LifeGold** [comment]
So I figured it would be just a VU then saw the subject and asked a question. I hope that will soon be ready . I would like to test and look at her .

**Comment by emperorstarfinder** [comment]
Closing as this has been answered.
